### ISSUE TITLE
Definição de Funcionalidades

### ISSUE THREAD

**Issue by ptv1p3r** [ptv1p3r/ptm_frontend#12]
Definição das funcionalidades e menus esperadas e indicadas no frontend.
Definição da estrutura para as funcionalidades e menus

**Comment by lireupt** [comment]
Após reunião com equipe de direito, ficou definido que a estrutura será a mesma do template, bem como os menus.
A criação de uma área pessoal onde o usuário irá fazer a sua gestão de bens adquiridos, com um login/logout a partir do template principal como funcionalidade principal do sistema.
O template principal terá que ter a explicação do projeto, especificações das árvores, patrocinadores, e o que suscitar interesse para o projeto. 
Novas views, serão adicionadas novas á estrutura já existente com o material a ser enviado para complementar o sistema.
Ficou também definido que serão realizadas reuniões semanais com a equipe de direito, com o propósito de irmos afinando pormenores.
