### ISSUE TITLE
Sistema de Login/Logout backoffice

### ISSUE THREAD

**Issue by ptv1p3r** [ptv1p3r/ptm_frontend#17]
Criar sistema de login/logout de entrada no backoffice
- consideração com jws tokens access token e refresh token
- consideração com segurança login em backoffice apenas autorizado pela segurança

**Comment by AndMJ** [comment]
ate agora faz login simples:

- com validaçao da api
- guarda tokens e userdata na $_SESSION
- login de pagina em pagina (neste caso so funciona ainda no dashboard e nos groups)

TODO:

- encriptar password no login
- encriptar password na criaçao de um novo user
- validar user group e respetiva security table
-

**Comment by ptv1p3r** [comment]
Awesome work
