### ISSUE TITLE
Galeria de imagens

### ISSUE THREAD

**Issue by ptv1p3r** [ptv1p3r/ptm_frontend#6]
Garantir a consistencia e qualidade da imagens para o template
Garantir medidas, resulução e compressão das imagens usados em todo o layout
Garantir imagens e direitos de autor das usadas

**Comment by lireupt** [comment]
Estou a aguardar por conteúdos digitais que vão ser enviados pela CM Monchique.

**Comment by lireupt** [comment]
Alguns conteúdos digitais já foram adicionados ao template, e foi solicitado á equipa de direito o envio de mais conteúdos.

**Comment by lireupt** [comment]
Ja recebi mais conteudos do professor vitor, irei adicionar no drive.

**Comment by lireupt** [comment]
todas as imagens adicionadas que o clinte enviou
