### ISSUE TITLE
Bootstap/jquery 

### ISSUE THREAD

**Issue by ptv1p3r** [ptv1p3r/ptm_frontend#7]
Normalizar todas as funcoes de bootstrap e jquery tanto no frontend como no backoffice
Podemos usar CDN, ou local, mas de preferencia CDN

**Comment by lireupt** [comment]
Frontend com CND e links do CSS normalizados, para correr a partir da web.

**Comment by AndMJ** [comment]
Backoffice com CDNs normalizados.
