### ISSUE TITLE
Gateway de Pagamentos

### ISSUE THREAD

**Issue by ptv1p3r** [ptv1p3r/ptm_frontend#8]
Criar registo na ifthenpay de forma a permitir a incorporação do gateway de pagamentos
Assim que possivel temos que ter o acesso ao gateway.

**Comment by lireupt** [comment]
Na reunião com a equipe de direito, ficou definido que o encargo desta matéria, será da responsabilidade deles, em que um dos elementos afirmou que já estava a tratar desta funcionalidade com uma empresa do conhecimento dele.
A equipe de EI somente ficará a aguardar pela credenciais de acesso ao gateway de pagamentos.
